services:
  angular-frontend:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4200:4200"
    command: bash -c "npm install -g @angular/cli && npm install && ng serve --host 0.0.0.0"
    depends_on:
      - meilisearch

  meilisearch:
    image: getmeili/meilisearch:v1.15
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: "masterkey"
    volumes:
      - ./meili_data:/meili_data
